# Generated by Django 4.2.5 on 2023-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isEditing',
            field=models.BooleanField(default=False),
        ),
    ]
